packages:
  - apps/*
  - packages/*
  - extensions/*

catalog:
  '@eslint/js': 9.37.0
  '@types/node': 24.7.1
  '@types/react': ^19
  '@types/react-dom': ^19
  '@vitejs/plugin-react': 5.0.4
  '@xyflow/react': ^12.0.0
  'class-variance-authority': 0.7.1
  'clsx': 2.1.1
  'commander': 12.1.0
  'eslint': 9.37.0
  'lucide-react': 0.545.0
  'prettier': 3.6.2
  'react': 19.1.0
  'react-dom': 19.1.0
  'tailwind-merge': 3.3.1
  'tailwindcss': ^4
  'turbo': 2.6.0
  'typescript': 5.9.3
  'typescript-eslint': 8.46.0
  'tsup': 8.5.0
  'tsx': 4.19.2
  'vite': 7.1.7
  '@radix-ui/react-accordion': 1.2.12
  '@radix-ui/react-avatar': 1.1.11
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-dropdown-menu': 2.1.16
  '@radix-ui/react-popover': 1.1.15
  '@radix-ui/react-select': 2.2.6
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-tabs': 1.1.13
  '@radix-ui/react-tooltip': 1.2.8
  '@tailwindcss/postcss': ^4
  'babel-plugin-react-compiler': 19.1.0-rc.3
  'cssnano': ^7.0.7
  'eslint-plugin-react-hooks': 5.2.0
  'eslint-plugin-react-refresh': 0.4.22
  'globals': 16.4.0
  'recharts': 2.15.4
  'cmdk': 1.1.1

