import { lazy, Suspense, useCallback, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { CircuitBoard, Layers3, Link2, Loader2, ShieldAlert } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "~/components/ui/tabs";
import { ResourceList } from "~/components/ResourceList";
import { ResourceDetail } from "~/components/ResourceDetail";
import { PendingOperationsList } from "~/components/PendingOperationsList";
import { ErrorBoundary } from "~/components/ErrorBoundary";
import { GlobalSearch } from "~/components/GlobalSearch";
import { StateFileUpload } from "~/components/StateFileUpload";
import * as State from "@sst-toolkit/core/state";
import * as Relationships from "@sst-toolkit/core/relationships";
import * as Workflow from "@sst-toolkit/core/workflow";
import type { ISSTState, ISSTResource } from "@sst-toolkit/shared/types/sst";
import { Spinner } from "~/components/ui/spinner";

const LazyWorkflowCanvas = lazy(() =>
  import("~/components/workflow/WorkflowCanvas").then((module) => ({
    default: module.WorkflowCanvas,
  }))
);

interface IAppShellProps {
  centered?: boolean;
  children: ReactNode;
}

function AppShell({ centered = false, children }: IAppShellProps) {
  return (
    <div className="explorer-glass-app">
      <main className={`explorer-shell${centered ? " explorer-shell-centered" : ""}`}>{children}</main>
    </div>
  );
}

function App() {
  const [state, setState] = useState<ISSTState | null>(null);
  const [selectedResource, setSelectedResource] = useState<ISSTResource | null>(null);
  const [nodes, setNodes] = useState<ReturnType<typeof State.parseState>>([]);
  const [loadingError, setLoadingError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleFileUpload = useCallback(async (file: File) => {
    setIsLoading(true);
    setLoadingError(null);

    try {
      const text = await file.text();
      const parsedState = JSON.parse(text) as ISSTState;
      const parsedNodes = State.parseState(parsedState);

      setState(parsedState);
      setNodes(parsedNodes);
      setSelectedResource(parsedState.latest.resources[0] ?? null);
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : "Failed to parse state file";
      setLoadingError(errorMessage);
      setState(null);
      setSelectedResource(null);
      setNodes([]);
    } finally {
      setIsLoading(false);
    }
  }, []);

  const handleResourceSelect = useCallback((resource: ISSTResource) => {
    setSelectedResource(resource);
  }, []);

  const allResources = useMemo(() => state?.latest.resources ?? [], [state?.latest.resources]);

  const pendingOperations = useMemo(
    () => state?.latest.pending_operations ?? [],
    [state?.latest.pending_operations]
  );

  const pendingOperationsResources = useMemo(
    () => pendingOperations.map((operation) => operation.resource),
    [pendingOperations]
  );

  const workflow = useMemo(() => {
    if (allResources.length === 0) {
      return { nodes: [], edges: [] };
    }

    const relationships = Relationships.parseResourceRelationships(allResources);
    return Workflow.buildWorkflow(allResources, relationships);
  }, [allResources]);

  const summary = useMemo(() => {
    const providerSet = new Set<string>();
    const categorySet = new Set<string>();

    for (const resource of allResources) {
      providerSet.add(State.getResourceProvider(resource.type));
      categorySet.add(State.getResourceTypeCategory(resource.type, resource));
    }

    return {
      providers: providerSet.size,
      categories: categorySet.size,
    };
  }, [allResources]);

  if (isLoading) {
    return (
      <AppShell centered>
        <section className="explorer-glass-panel explorer-state-card">
          <div className="explorer-loading-pill">
            <Spinner className="size-4" />
            Parsing state file
          </div>
          <h1 className="explorer-state-title">Hydrating infrastructure graph</h1>
          <p className="explorer-state-description">
            We are validating your SST snapshot, extracting relationships, and preparing explorer surfaces.
          </p>
        </section>
      </AppShell>
    );
  }

  if (!state) {
    return (
      <AppShell centered>
        <section className="explorer-glass-panel explorer-state-card">
          <p className="explorer-eyebrow">SST Infrastructure Observatory</p>
          <h1 className="explorer-state-title">Upload your state snapshot</h1>
          <p className="explorer-state-description">
            Load a Pulumi state export generated by SST to inspect resources, pending operations, and dependency flow in one command surface.
          </p>

          <StateFileUpload onFileUpload={handleFileUpload} />

          {loadingError && (
            <div className="explorer-inline-alert" role="alert">
              <p>{loadingError}</p>
            </div>
          )}

          <div className="explorer-command-block">
            <p>Export Command</p>
            <code>npx sst state export --stage dev &gt; state.json</code>
          </div>
        </section>
      </AppShell>
    );
  }

  const lastUpdated = new Date(state.latest.manifest.time).toLocaleString();

  return (
    <ErrorBoundary>
      <AppShell>
        <section className="explorer-glass-panel explorer-header">
          <div className="explorer-headline-row">
            <div className="explorer-headline-block">
              <p className="explorer-eyebrow">SST Infrastructure Observatory</p>
              <h1 className="explorer-title">SST State Visualizer</h1>
              <p className="explorer-subtitle">
                Track deployed resources, pending mutations, and graph dependencies for stack <strong>{state.stack}</strong>.
              </p>
              <div className="explorer-meta-row">
                <span className="explorer-meta-pill">manifest v{state.latest.manifest.version}</span>
                <span className="explorer-meta-pill">last synced {lastUpdated}</span>
                <span className="explorer-meta-pill">stack {state.stack}</span>
              </div>
            </div>

            <div className="explorer-actions">
              <StateFileUpload onFileUpload={handleFileUpload} />
              <GlobalSearch
                resources={allResources}
                pendingOperationsResources={pendingOperationsResources}
                onSelectResource={handleResourceSelect}
              />
            </div>
          </div>

          <div className="explorer-metrics" role="list" aria-label="Infrastructure summary">
            <article className="explorer-metric-card" role="listitem">
              <p className="explorer-metric-label">Resources</p>
              <p className="explorer-metric-value">{allResources.length}</p>
              <p className="explorer-metric-note">tracked in current snapshot</p>
            </article>
            <article className="explorer-metric-card" role="listitem">
              <p className="explorer-metric-label">Pending Ops</p>
              <p className="explorer-metric-value">{pendingOperations.length}</p>
              <p className="explorer-metric-note">create, update, delete, replace</p>
            </article>
            <article className="explorer-metric-card" role="listitem">
              <p className="explorer-metric-label">Providers</p>
              <p className="explorer-metric-value">{summary.providers}</p>
              <p className="explorer-metric-note">SST, AWS, and supporting services</p>
            </article>
            <article className="explorer-metric-card" role="listitem">
              <p className="explorer-metric-label">Relationships</p>
              <p className="explorer-metric-value">{workflow.edges.length}</p>
              <p className="explorer-metric-note">across {summary.categories} categories</p>
            </article>
          </div>
        </section>

        <section className="explorer-glass-panel explorer-tabs-shell">
          <Tabs defaultValue="explorer">
            <div className="explorer-tab-head">
              <TabsList className="explorer-tabs-list">
                <TabsTrigger value="explorer" className="explorer-tab-trigger">
                  <Layers3 className="size-3.5" />
                  Explorer
                </TabsTrigger>
                {pendingOperations.length > 0 && (
                  <TabsTrigger value="pending" className="explorer-tab-trigger">
                    <ShieldAlert className="size-3.5" />
                    Pending
                  </TabsTrigger>
                )}
                <TabsTrigger value="workflow" className="explorer-tab-trigger">
                  <CircuitBoard className="size-3.5" />
                  Workflow
                </TabsTrigger>
              </TabsList>
              <p className="explorer-tab-hint">
                <Link2 className="inline size-3.5 align-[-0.15rem]" /> Select a resource to sync detail and workflow context.
              </p>
            </div>

            <TabsContent value="explorer" className="explorer-tab-content">
              <div className="explorer-main-grid">
                <div className="explorer-main-panel">
                  <ResourceList
                    nodes={nodes}
                    onSelectResource={handleResourceSelect}
                    selectedUrn={selectedResource?.urn}
                  />
                </div>
                <div className="explorer-main-panel">
                  <ResourceDetail resource={selectedResource} />
                </div>
              </div>
            </TabsContent>

            {pendingOperations.length > 0 && (
              <TabsContent value="pending" className="explorer-tab-content">
                <div className="explorer-main-grid">
                  <div className="explorer-main-panel">
                    <PendingOperationsList
                      operations={pendingOperations}
                      onSelectResource={handleResourceSelect}
                      selectedUrn={selectedResource?.urn}
                    />
                  </div>
                  <div className="explorer-main-panel">
                    <ResourceDetail resource={selectedResource} />
                  </div>
                </div>
              </TabsContent>
            )}

            <TabsContent value="workflow" className="explorer-tab-content">
              <div className="explorer-workflow-panel">
                <Suspense
                  fallback={
                    <div className="explorer-workflow-fallback">
                      <div className="explorer-loading-pill">
                        <Loader2 className="size-4 animate-spin" />
                        Rendering workflow
                      </div>
                    </div>
                  }
                >
                  <LazyWorkflowCanvas
                    nodes={workflow.nodes}
                    edges={workflow.edges}
                    onNodeSelect={(nodeId) => {
                      const resource = allResources.find((item) => item.urn === nodeId);
                      if (resource) {
                        handleResourceSelect(resource);
                      }
                    }}
                    selectedNodeId={selectedResource?.urn}
                  />
                </Suspense>
              </div>
            </TabsContent>
          </Tabs>
        </section>
      </AppShell>
    </ErrorBoundary>
  );
}

export default App;
